apiVersion: v1
kind: Service
metadata:
  labels:
    name: app07
  name: app07
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    name: app07
  sessionAffinity: None
  type: ClusterIP
